default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DB_HOST', 'db') %>
  username: root
  password:
  port: 3306
  timeout: 5000
  charset: utf8
  collation: utf8_unicode_ci

rds: &rds
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>

development:
  <<: *default
  database: todo-api_development

test:
  <<: *default
  database: todo-api_test

production:
  <<: *default
  <<: *rds
