branch-defaults:
  elastic-beanstalk:
    environment: todo-nuxt-rails-dev
global:
  application_name: todo-nuxt-rails
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Ruby 2.6 (Puma)
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
